(*
  licenzio - A CLI tool for adding license files to projects
  Khalid B. | @khalidbelk, 2026
  File: src/license.ml
*)

open File
open Io_msg

type license =
  | APACHE_2
  | ARTISTIC_2
  | BSD_3_Clause
  | CC_BY_4
  | EUPL_1_2
  | GNU_AGPL_3
  | GNU_GPL_2
  | GNU_LGPL_3
  | MIT
  | MOZILLA

let all_licenses = [
  (APACHE_2,      [%blob "../licenses/apache_2.0.txt"]);
  (ARTISTIC_2,    [%blob "../licenses/artistic_2.0.txt"]);
  (BSD_3_Clause,  [%blob "../licenses/bsd_3_clause.txt"]);
  (CC_BY_4,       [%blob "../licenses/cc_attrib_4.txt"]);
  (EUPL_1_2,      [%blob "../licenses/eupl_1.2.txt"]);
  (GNU_AGPL_3,    [%blob "../licenses/gnu_agpl-v3.txt"]);
  (GNU_GPL_2,     [%blob "../licenses/gnu_gpl-v3.txt"]);
  (GNU_LGPL_3,    [%blob "../licenses/gnu_lgpl-v3.txt"]);
  (MIT,           [%blob "../licenses/mit.txt"]);
  (MOZILLA,       [%blob "../licenses/mozilla.txt"])
]

let license_of_string str : license option =
  match str with
  | "apache" -> Some (APACHE_2)
  | "artistic" -> Some (ARTISTIC_2)
  | "bsd" -> Some (BSD_3_Clause)
  | "cc" -> Some (CC_BY_4)
  | "eupl" -> Some (EUPL_1_2)
  | "agpl" -> Some (GNU_AGPL_3)
  | "gpl" -> Some (GNU_GPL_2)
  | "lgpl" -> Some (GNU_LGPL_3)
  | "mit" -> Some (MIT)
  | "mozilla" -> Some (MOZILLA)
  | _ -> None

let cmd_of_license l : string =
  match l with
  | APACHE_2 -> "apache"
  | ARTISTIC_2 -> "artistic"
  | BSD_3_Clause -> "bsd"
  | CC_BY_4 -> "cc"
  | EUPL_1_2 -> "eupl"
  | GNU_AGPL_3 -> "agpl"
  | GNU_GPL_2 -> "gpl"
  | GNU_LGPL_3 -> "lgpl"
  | MIT -> "mit"
  | MOZILLA -> "mozilla"

let title_of_license = function
  | APACHE_2      -> "Apache License (Version 2.0)"
  | ARTISTIC_2    -> "The Artistic License 2.0"
  | BSD_3_Clause  -> "BSD 3-Clause License"
  | CC_BY_4       -> "Creative Commons - Attribution 4.0 International"
  | EUPL_1_2      -> "European Union Public License 1.2"
  | GNU_AGPL_3    -> "GNU Affero General Public License v3.0"
  | GNU_GPL_2     -> "GNU General Public License v2.0"
  | GNU_LGPL_3    -> "GNU Lesser General Public License v3.0"
  | MIT           -> "MIT License"
  | MOZILLA       -> "Mozilla Public License 2.0"

let create_license_file ?(out_dir="./") str =
  let out_filename = "LICENSE" in
  let out_filepath = Filename.concat out_dir out_filename in
  match license_of_string str with
    | Some valid ->
        Printf.printf "Creating '%s'...\n" (title_of_license valid);
        let license_text =  List.assoc valid all_licenses in
        let attributed = license_text ^ "\n" ^ "Generated by Licenzio v" ^ version in
        write_to_file attributed out_filepath;
        exit 0
    | None ->
        Printf.printf "The provided string doesn't match any supported license.\n";
        print_use_help ();
        exit 1;